### Get courses
GET {{courses}}

### Create course
POST {{courses}}/
Content-Type: application/json

{
  "name": "Aprende microservicios con spring"
}

### Get course detail
GET {{courses}}/1
Authorization: Bearer {{token}}

### Create user into course
POST {{courses}}/create-user/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Luis Cruz",
  "email": "test@angelcruzl.dev",
  "password": "123456"
}

### Assign user into course
PUT {{courses}}/assign-user/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "Ángel Cruz",
  "email": "me@angelcruzl.dev",
  "password": "123456"
}

### Unassign user into course
DELETE {{courses}}/unassign-user/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "Ángel Cruz",
  "email": "me@angelcruzl.dev",
  "password": "123456"
}
