apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: courses-data-pvc
spec:
  volumeName: courses-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
