apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-courses
  template:
    metadata:
      labels:
        app: msvc-courses
    spec:
      containers:
        - image: angelcruzl/msvc-courses:latest
          name: msvc-courses
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: db_host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: msvc-courses
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: msvc-courses
                  key: db_pass
            - name: MSVC_USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: msvc_users_url
