apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-users
  template:
    metadata:
      labels:
        app: msvc-users
    spec:
      containers:
        - image: angelcruzl/msvc-users:latest
          name: msvc-users
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-users
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-users
                  key: db_host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-users
                  key: db_name
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: msvc-users
                  key: db_user
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: msvc-users
                  key: db_pass
            - name: MSVC_COURSES_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-users
                  key: msvc_courses_url
