apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-msvc-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-msvc-courses
  template:
    metadata:
      labels:
        app: db-msvc-courses
    spec:
      containers:
        - image: postgres:14.3
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: msvc_courses
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Secret123
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: courses-data
      volumes:
        - name: courses-data
          hostPath:
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate
