apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-courses
  template:
    metadata:
      labels:
        app: msvc-courses
    spec:
      containers:
        - image: angelcruzl/msvc-courses:latest
          name: msvc-courses
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DB_HOST
              value: db-msvc-courses:5432
            - name: DB_NAME
              value: msvc_courses
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: Secret123
            - name: MSVC_USERS_URL
              value: msvc-users:8001
