apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-data-pvc
spec:
  volumeName: users-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
