version: '3.7'

services:
  db-msvc-users:
    container_name: db-msvc-users
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: msvc_users
      MYSQL_ROOT_PASSWORD: Secret123
      MYSQL_PASSWORD: Secret123
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - spring

  db-msvc-courses:
    container_name: db-msvc-courses
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: msvc_courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Secret123
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init-scripts/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    networks:
      - spring

  msvc-users:
    container_name: msvc-users
    depends_on:
      - db-msvc-users
    image: angelcruzl/msvc-users:latest
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ../msvc-users/.env
    networks:
      - spring

  msvc-courses:
    container_name: msvc-courses
    depends_on:
      - db-msvc-courses
      - msvc-users
    image: angelcruzl/msvc-courses:latest
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - ../msvc-courses/.env
    networks:
      - spring

volumes:
  sql-data:
    name: sql-data
  postgres:
    name: postgres

networks:
  spring:
