spring:
  security:
    oauth2:
      client:
        registration:
          msvc-users-client:
            provider: spring
            client-id: users-client
            client-secret: Secret123
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8001/authorized"
            scope: read
            client-name: msvc-users-client
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
