name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker-compose -f docker-compose.dev.yml build

      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io

      - name: Push Docker images
        run: docker-compose push

      - name: Prepare docker-compose file
        run: |
          sed -i 's/\${secrets.MSVC_USERS_DB_HOST}/'"${{ secrets.MSVC_USERS_DB_HOST }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_USERS_DB_NAME}/'"${{ secrets.MSVC_USERS_DB_NAME }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_USERS_DB_USER}/'"${{ secrets.MSVC_USERS_DB_USER }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_USERS_DB_PASS}/'"${{ secrets.MSVC_USERS_DB_PASS }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_COURSES_URL}/'"${{ secrets.MSVC_COURSES_URL }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_COURSES_DB_HOST}/'"${{ secrets.MSVC_COURSES_DB_HOST }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_COURSES_DB_NAME}/'"${{ secrets.MSVC_COURSES_DB_NAME }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_COURSES_DB_USER}/'"${{ secrets.MSVC_COURSES_DB_USER }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_COURSES_DB_PASS}/'"${{ secrets.MSVC_COURSES_DB_PASS }}"'/g' docker-compose.prod.yml
          sed -i 's/\${secrets.MSVC_USERS_URL}/'"${{ secrets.MSVC_USERS_URL }}"'/g' docker-compose.prod.yml

      - name: Transfer docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: ${{ secrets.VPS_PATH }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker-compose -f ${{ secrets.VPS_PATH }}/docker-compose.prod.yml down
            docker-compose -f ${{ secrets.VPS_PATH }}/docker-compose.prod.yml up -d
